### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by bwmoths** [geoinnova/geoeasin#4]
When searching for species the message "Connection Error" is displayed in place of the "Info" legend below the species list area.

Open plugin
type species name to search for in the box
click on "search"
"Info" changes to "Connection Error"

Nothing is displayed in the results area.

This appears to have occured since installing QGIS 3.28.2LTR
Still same problem with QGIS 3.28.5

**Desktop**
 - OS: Windows 10
 - Browser Microsoft Edge

**Comment by sigdeletras** [comment]
Greetings

We have verified on the project website that the API endpoints have been modified.
This entails a modification to the plugin code which we will address where possible.

Thank you very much for notifying.

**Comment by bwmoths** [comment]
Thank you, I look forward to to the plugin working again !
Martin

**Comment by bwmoths** [comment]
Hi, it is now 4 months since I reported this problem ! Is anyone going to fix the problem or must I just delete what should be a worthwhile plugin as useless !

Martin

**Comment by sigdeletras** [comment]
Hi Martin

GeoEASIN is an open source and non-profit QGIS plugin. From this point of view, there are no human resources specifically dedicated to its maintenance. This means that the development team altruistically tries to take time to solve possible errors that arise or make the necessary improvements or changes.

As it is not a commercial product or contracted by a client, there is also no obligation regarding response time.

In the event that there is some personal or professional need to solve this issue, would you be willing to spend time reviewing the changes to the EASIN API and tell us what has specifically changed? You have all the code available in the repository and we are open to Pull Requests.

There is also another possibility: how much money would you be willing to invest to have a developer correct it?

As it seems that these questions have a complex answer, I can only tell you that we will continue trying to solve the issue when possible.

If faced with this situation, you still think that the plugin is 'useless' we are very sorry.

Patricio

**Comment by sigdeletras** [comment]
Hi!

The bug has been fixed in the new version (v.2) which is now available on the official QGIS plugins repository (https://plugins.qgis.org/plugins/geoeasin/).

It is only necessary to access QGIS and update the plugin to the latest version.

All the best

04.09.2023 V2.0: New realese: 
- Changes for the new EASIN API. 
- New filters in the form. 
- Statistics on fields of the grid layer in the Log tab

**Comment by bwmoths** [comment]
Hi Patricio

Thank you ! Yes, all works fine again now.

MartinMartin Love FRES FLSWhitebridge FarmSedgehillShaftesburyDorsetSP7 9JT07884 ***@***.***

Hi!
The bug has been fixed in the new version (v.2) which is now available on the official QGIS plugins repository (https://plugins.qgis.org/plugins/geoeasin/).
It is only necessary to access QGIS and update the plugin to the latest version.
All the best
04.09.2023 V2.0: New realese:

 Changes for the new EASIN API.
 New filters in the form.
 Statistics on fields of the grid layer in the Log tab

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.

--
